language: java
jdk:
- oraclejdk8
sudo: required

script: gradle check
branches:
only: development

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - lourdes.villca@fundacion-jala.org